GET http://localhost:3000/api/jobs

### 
GET http://localhost:3000/api/jobs/61d75e6b73affc717db18c1a

###
POST http://localhost:3000/api/jobs
Content-Type: application/json

{
  "title": "Testing 123 123 13",
  "content": "This is my test, hop you like it"
}