###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "companyName": "",
  "name": "",
  "email": "",
  "phone": "",
  "password": "",
  "passwordConfirm": ""
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "jim@aol.com",
  "password": "password"
}