###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "companyName": "",
  "name": "",
  "email": "",
  "phone": "",
  "password": "",
  "passwordConfirm": ""
}

### Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "joe@aol.com",
  "password": "password"
}